env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  'arrow-body-style': 1,
  'no-unused-vars': 1,
  'import/extensions': 0,
  'import/no-unresolved': 0,
  'import/prefer-default-export': 0,
  'react/function-component-definition': 0,
  'react/no-unused-prop-types': 0,
  'react/require-default-props': 0,
  'react/jsx-props-no-spreading': 0,
  'react/jsx-filename-extension': [
    1, 
    { "extensions": [".jsx", ".tsx"] }
  ],
}
